server.port=8080
spring.application.name=numerical-methods-lab

logging.level.yaart.s468198=DEBUG
logging.level.org.springframework.web=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

logging.file.name=logs/application.log
logging.file.max-size=10MB
logging.file.max-history=7